name: Send Email and Deploy

on:
    workflow_dispatch:
        schedule:
            - cron: '0 5-15/3 * * 1-5'

jobs:
    main:
        timeout-minutes: 60

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm install -g yarn && yarn
            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps
            - name: Run Playwright tests
              run: yarn playwright test
              env:
                  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
                  EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}
                  EMAIL_TO: ${{ secrets.EMAIL_TO }}
                  SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
